// go to --> https://www.npmjs.com/package/@ducanh2912/next-pwa
// go to --> https://ducanh-next-pwa.vercel.app/docs/next-pwa/getting-started
// npm i @ducanh2912/next-pwa


// ================ next.config.js ==================//

/** @type {import('next').NextConfig} */

const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  cacheOnFrontEndNav: true,
  aggressiveFrontEndNavCaching: true,
  disable: false,
  // swcMinify: true,
  workboxOptions:{
    disableDevLogs: true
  }
});

const nextConfig = {}

module.exports = withPWA(nextConfig);



// ========================================//

// goole search --> Next js pwa mainifest generator 
// go to --> https://www.simicart.com/manifest-generator.html/
// fill the form and click --> Generate Menifest (it will auto download manifest file)
// past the menifest file to the --> public folder


// ================= app/public/manifest.webmanifest ==================//
// this file is downloaded
{
    "name": "Test PWA app",
    "short_name": "PWA Test",
    "icons": [
      {
        "src": "/icon-192x192.png",
        "sizes": "192x192",
        "type": "image/png",
        "purpose": "any maskable"
      },
      {
        "src": "/icon-384x384.png",
        "sizes": "384x384",
        "type": "image/png"
      },
      {
        "src": "/icon-512x512.png",
        "sizes": "512x512",
        "type": "image/png"
      }
    ],
    "theme_color": "#FFFFFF",
    "background_color": "#FFFFFF",
    "start_url": "/",
    "display": "standalone",
    "orientation": "portrait"
  }



// ================== app/layout.js===================/
// add manifest
export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};
  
